Repository prgrms-be-devcourse/NBE5-7-1-Team02, pull requests merged in 2025-04, with the labels that each got.

#12 feat(menu) : 메뉴생성 기능 구현
  build.gradle
  src/main/java/easy/gc_coffee_api/controller/MenuController.java
  src/main/java/easy/gc_coffee_api/dto/CreateMenuRequestDto.java
  src/main/java/easy/gc_coffee_api/dto/CreateMenuResponseDto.java
  src/main/java/easy/gc_coffee_api/entity/Thumnail.java
  src/main/java/easy/gc_coffee_api/entity/common/Category.java
  src/main/java/easy/gc_coffee_api/exception/GCException.java
  src/main/java/easy/gc_coffee_api/exception/GlobalExceptionHandler.java
  src/main/java/easy/gc_coffee_api/exception/ThumnailCreateException.java
  src/main/java/easy/gc_coffee_api/usecase/menu/CreateMenuUsecase.java
  src/main/java/easy/gc_coffee_api/usecase/menu/MenuSaver.java
  src/main/java/easy/gc_coffee_api/usecase/menu/ThumnailFatory.java
  src/test/java/easy/gc_coffee_api/entity/ThumnailTest.java
  src/test/java/easy/gc_coffee_api/entity/common/CategoryTest.java
  src/test/java/easy/gc_coffee_api/usecase/menu/CreateMenuUsecaseTest.java
  src/test/java/easy/gc_coffee_api/usecase/menu/ThumnailFatoryTest.java
Labels: feature

#14 feat(menu): 커피 메뉴 조회 기능 구현
  src/main/java/easy/gc_coffee_api/controller/MenuController.java
  src/main/java/easy/gc_coffee_api/dto/MenuResponseDto.java
  src/main/java/easy/gc_coffee_api/dto/MenusResponseDto.java
  src/main/java/easy/gc_coffee_api/entity/Menu.java
  src/main/java/easy/gc_coffee_api/entity/Thumnail.java
  src/main/java/easy/gc_coffee_api/repository/MenuRepository.java
  src/main/java/easy/gc_coffee_api/usecase/menu/GetMenusUseCase.java
  src/test/java/easy/gc_coffee_api/usecase/menu/GetMenusUseCaseTests.java
Labels: feature

#16 feat(file): 정적 리소스 서빙 기능 구현
  src/main/java/easy/gc_coffee_api/config/GlobalCorsConfig.java
  src/main/java/easy/gc_coffee_api/config/WebConfig.java
  src/main/java/easy/gc_coffee_api/dto/file/UploadFileResponseDto.java
  src/main/java/easy/gc_coffee_api/entity/File.java
  src/main/java/easy/gc_coffee_api/exception/GlobalExceptionHandler.java
  src/main/java/easy/gc_coffee_api/usecase/file/UploadFileUseCase.java
  src/main/java/easy/gc_coffee_api/usecase/file/strategy/LocalFileStorageStrategy.java
  src/main/java/easy/gc_coffee_api/usecase/file/strategy/StorageStrategy.java
  src/main/java/easy/gc_coffee_api/usecase/file/vo/FileUrl.java
  storage/default.jpg
Labels: feature

#20 feat(order):주문기능 구현하였습니다.
  src/main/java/easy/gc_coffee_api/controller/OrderMenuController.java
  src/main/java/easy/gc_coffee_api/dto/AddressDto.java
  src/main/java/easy/gc_coffee_api/dto/OrderItemDto.java
  src/main/java/easy/gc_coffee_api/dto/OrderRequestDto.java
  src/main/java/easy/gc_coffee_api/entity/Menu.java
  src/main/java/easy/gc_coffee_api/entity/OrderMenu.java
  src/main/java/easy/gc_coffee_api/repository/OrderMenuRepository.java
  src/main/java/easy/gc_coffee_api/usecase/order/OrderMenuUserCase.java
  src/main/java/easy/gc_coffee_api/usecase/order/OrderMenus.java
  src/test/java/easy/gc_coffee_api/controller/OrderMenuControllerTest.java
  src/test/java/easy/gc_coffee_api/usecase/order/OrderMenuUserCaseTest.java
  src/test/java/easy/gc_coffee_api/usecase/order/OrderMenuUserCaseTest_ERROR.java
Labels: feature

#18 섬네일 생성기능 정책 변경에따른 수정
  src/main/java/easy/gc_coffee_api/entity/File.java
  src/main/java/easy/gc_coffee_api/entity/Thumnail.java
  src/main/java/easy/gc_coffee_api/usecase/menu/ThumnailFatory.java
  src/test/java/easy/gc_coffee_api/usecase/menu/ThumnailFatoryTest.java
Labels: feature

#17 feat(menu): 커피 메뉴 수정 기능 구현
  src/main/java/easy/gc_coffee_api/controller/MenuController.java
  src/main/java/easy/gc_coffee_api/dto/UpdateMenuRequestDto.java
  src/main/java/easy/gc_coffee_api/entity/Menu.java
  src/main/java/easy/gc_coffee_api/exception/menu/InvalidMenuCategoryException.java
  src/main/java/easy/gc_coffee_api/exception/menu/InvalidMenuNameException.java
  src/main/java/easy/gc_coffee_api/exception/menu/InvalidMenuPriceException.java
  src/main/java/easy/gc_coffee_api/exception/menu/MenuNotFoundException.java
  src/main/java/easy/gc_coffee_api/usecase/menu/UpdateMenuUsecase.java
  src/test/java/easy/gc_coffee_api/usecase/menuupdate/UpdateMenuUsecaseTest.java
Labels: feature

#30 feat(menu): 커피 메뉴 단일 조회 기능 구현
  backend/src/main/java/easy/gc_coffee_api/controller/MenuController.java
  backend/src/main/java/easy/gc_coffee_api/dto/MenuResponseDto.java
  backend/src/main/java/easy/gc_coffee_api/repository/MenuRepository.java
  backend/src/main/java/easy/gc_coffee_api/usecase/file/FileUrlTranslator.java
  backend/src/main/java/easy/gc_coffee_api/usecase/file/strategy/LocalFileStorageStrategy.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/CreateMenuUsecase.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/GetMenuUseCase.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/GetMenusUseCase.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/UpdateMenuUsecase.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/dto/MenuData.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/dto/MenuDatas.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/helper/MenuReader.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/helper/MenuSaver.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/helper/ThumbnailFactory.java
  backend/src/test/java/easy/gc_coffee_api/repository/MenuRepositoryTests.java
  backend/src/test/java/easy/gc_coffee_api/usecase/file/UploadFileUseCaseTest.java
  backend/src/test/java/easy/gc_coffee_api/usecase/menu/CreateMenuUsecaseTest.java
  backend/src/test/java/easy/gc_coffee_api/usecase/menu/GetMenuUseCaseTests.java
  backend/src/test/java/easy/gc_coffee_api/usecase/menu/GetMenusUseCaseTests.java
  backend/src/test/java/easy/gc_coffee_api/usecase/menu/ThumbnailFactoryTest.java
  backend/src/test/java/easy/gc_coffee_api/usecase/menuupdate/UpdateMenuUsecaseTest.java
Labels: feature

#34 refactor(menu): 단일 메뉴 삭제의 response 형식 수정
  backend/src/main/java/easy/gc_coffee_api/controller/MenuController.java
  backend/src/main/java/easy/gc_coffee_api/usecase/menu/helper/MenuReader.java
Labels: refactor

#35 [feat] 주문내역 조회 기능 구현
  backend/src/main/java/easy/gc_coffee_api/controller/OrderMenuController.java
  backend/src/main/java/easy/gc_coffee_api/dto/OrderListResponseDto.java
  backend/src/main/java/easy/gc_coffee_api/dto/OrderMenuResponseDto.java
  backend/src/main/java/easy/gc_coffee_api/entity/OrderMenu.java
  backend/src/main/java/easy/gc_coffee_api/entity/Orders.java
  backend/src/main/java/easy/gc_coffee_api/repository/OrderMenuRepository.java
  backend/src/main/java/easy/gc_coffee_api/repository/OrderRepository.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/GetOrderListUsecase.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/OrderListResponseDtoMapper.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/dto/OrderMenuData.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/dto/OrderMenuDatas.java
  backend/src/test/java/easy/gc_coffee_api/usecase/order/GetOrderListUsecaseTest.java
Labels: feature

#38 feat(security): 어드민 로그인 구현
  backend/build.gradle
  backend/src/main/java/easy/gc_coffee_api/config/GlobalCorsConfig.java
  backend/src/main/java/easy/gc_coffee_api/config/SecurityConfig.java
  backend/src/main/java/easy/gc_coffee_api/controller/AuthController.java
  backend/src/main/java/easy/gc_coffee_api/controller/MenuController.java
  backend/src/main/java/easy/gc_coffee_api/repository/UserRepository.java
  backend/src/main/java/easy/gc_coffee_api/security/AdminDetails.java
  backend/src/main/java/easy/gc_coffee_api/security/AdminDetailsService.java
Labels: feature, fix

#40 feat(order) : 날짜별로 묶어서 읽어오는 기능 구현
  backend/src/main/java/easy/gc_coffee_api/controller/OrderMenuController.java
  backend/src/main/java/easy/gc_coffee_api/dto/OrderDateRangeDto.java
  backend/src/main/java/easy/gc_coffee_api/dto/OrderListResponseDto.java
  backend/src/main/java/easy/gc_coffee_api/dto/OrderMenuResponseDto.java
  backend/src/main/java/easy/gc_coffee_api/entity/common/BaseDateEntity.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/GetOrderListUsecase.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/OrderDataRange.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/OrderDateRangeRule.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/OrderListResponseDtoMapper.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/dto/OrderMenuData.java
  backend/src/test/java/easy/gc_coffee_api/usecase/order/GetOrderListUsecaseTest.java
Labels: feature

#47 feat(orders): 단건, 일괄 배송처리 구현
  backend/src/main/java/easy/gc_coffee_api/controller/OrderMenuController.java
  backend/src/main/java/easy/gc_coffee_api/entity/Orders.java
  backend/src/main/java/easy/gc_coffee_api/exception/order/OrderAlreadyShippedException.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/ShipOrderUseCase.java
  backend/src/main/java/easy/gc_coffee_api/usecase/order/ShipOrdersUseCase.java
Labels: feature

#51 feat(fe): 배송 관련 기능 api 연동, 배송일시 정보 상세 주문 컴포넌트에 추가
  backend/src/main/java/easy/gc_coffee_api/controller/OrderMenuController.java
  frontend/src/api/params/order/getOrderById.ts
  frontend/src/api/params/order/shipOrder.ts
  frontend/src/api/params/order/shipOrders.ts
  frontend/src/api/session/index.ts
  frontend/src/api/session/order/shipOrder.ts
  frontend/src/api/session/order/shipOrders.ts
  frontend/src/components/admin/menus/AdminMenuList.tsx
  frontend/src/components/admin/orders/AdminOrderList.tsx
  frontend/src/pages/admin/AdminHomePage.tsx
  frontend/src/pages/user/OrderLookUpPage.tsx
  frontend/src/pages/user/OrderSuccesPage.tsx
Labels: feature
